#!/usr/bin/with-contenv bash

cred_file="/etc/guacamole/user-mapping.xml"

if [[ -n "$GUAC_USER" ]]; then
  sed -i -e s%"\(username\=\).*"%"\1\"$GUAC_USER\""%g "$cred_file"
fi

if [[ -n "$GUAC_PASS" ]]; then
  sed -i -e s%"\(password\=\).*"%"\1\"$GUAC_PASS\""%g "$cred_file"
fi
